# Generated by Django 5.2.1 on 2025-06-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('distance_from_home', models.CharField(blank=True, max_length=255, null=True)),
                ('distance_from_last_transaction', models.CharField(blank=True, max_length=255, null=True)),
                ('ratio_to_median_purchase_price', models.CharField(blank=True, max_length=255, null=True)),
                ('repeat_retailer', models.IntegerField(blank=True, null=True)),
                ('used_chip', models.IntegerField(blank=True, null=True)),
                ('used_pin_number', models.IntegerField(blank=True, null=True)),
                ('online_order', models.IntegerField(blank=True, null=True)),
                ('fraud', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transactions',
                'managed': False,
            },
        ),
    ]
