# Generated by Django 5.2.1 on 2025-11-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionsTest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('distance_from_home', models.FloatField(blank=True, null=True)),
                ('distance_from_last_transaction', models.FloatField(blank=True, null=True)),
                ('ratio_to_median_purchase_price', models.FloatField(blank=True, null=True)),
                ('repeat_retailer', models.BooleanField(blank=True, null=True)),
                ('used_chip', models.BooleanField(blank=True, null=True)),
                ('used_pin_number', models.BooleanField(blank=True, null=True)),
                ('online_order', models.BooleanField(blank=True, null=True)),
                ('fraud', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transactions_test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('card_bin', models.CharField(blank=True, max_length=255, null=True)),
                ('card_last_four', models.CharField(blank=True, max_length=255, null=True)),
                ('card_expiry_month', models.IntegerField(blank=True, null=True)),
                ('card_expiry_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_info',
                'managed': False,
            },
        ),
    ]
