# Generated by Django 5.2.1 on 2025-11-05 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_transactionstest_userinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionstest',
            options={},
        ),
    ]
