# Generated by Django 5.2.1 on 2025-11-05 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_transactionstest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionstest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.userinfo'),
        ),
    ]
